export const cards = [
  {
    icon: 'light',
    state: 'on',
    title: 'Xiaomi Yeelight LED Smart Bulb',
    subTitle: 'Включено',
    size: 'l',
    type: 'light',
    tag: 'kitchen',
  },
  {
    icon: 'light',
    state: 'off',
    title: 'D-Link Omna 180 Cam',
    subTitle: 'Включится в 17:00',
    size: 'l',
    type: 'floor',
    tag: 'lights',
  },
  {
    icon: 'temp',
    state: 'off',
    title: 'Elgato Eve Degree Connected',
    subTitle: 'Выключено до 17:00',
    size: 'l',
    type: 'temp',
    tag: 'kitchen',
  },
  {
    icon: 'light',
    state: 'off',
    title: 'LIFX Mini Day & Dusk A60 E27',
    subTitle: 'Включится в 17:00',
    size: 'l',
    type: 'floor',
    tag: 'lights',
  },
  {
    icon: 'light',
    state: 'on',
    title: 'Xiaomi Mi Air Purifier 2S',
    subTitle: 'Включено',
    size: 'l',
    type: 'temp',
    tag: 'cameras',
  },
  {
    icon: 'light',
    state: 'off',
    title: 'Philips Zhirui',
    subTitle: 'Выключено',
    size: 'l',
    type: 'floor',
    tag: 'cameras',
  },
  {
    icon: 'light',
    state: 'on',
    title: 'Xiaomi Yeelight LED Smart Bulb',
    subTitle: 'Включено',
    size: 'l',
    type: 'temp',
    tag: 'kitchen',
  },
  {
    icon: 'light',
    state: 'off',
    title: 'D-Link Omna 180 Cam',
    subTitle: 'Включится в 17:00',
    size: 'l',
    tag: 'lights',
  },
  {
    icon: 'temp',
    state: 'off',
    title: 'Elgato Eve Degree Connected',
    subTitle: 'Выключено до 17:00',
    size: 'l',
    tag: 'kitchen',
  },
  {
    icon: 'light',
    state: 'off',
    title: 'LIFX Mini Day & Dusk A60 E27',
    subTitle: 'Включится в 17:00',
    size: 'l',
    tag: 'hall',
  },
  {
    icon: 'light',
    state: 'on',
    title: 'Xiaomi Mi Air Purifier 2S',
    subTitle: 'Включено',
    size: 'l',
    tag: 'lights',
  },
  {
    icon: 'light',
    state: 'off',
    title: 'Philips Zhirui',
    subTitle: 'Выключено',
    size: 'l',
    tag: 'hall',
  },
];

export const filter = {
  value: 'all',
  items: [
    { value: 'all', text: 'Все' },
    { value: 'kitchen', text: 'Кухня' },
    { value: 'hall', text: 'Зал' },
    { value: 'lights', text: 'Лампочки' },
    { value: 'cameras', text: 'Камеры' },
  ],
};
